console.log("first line");
console.log("second line");
console.log("third line");
console.log("fourth line");
console.log("fifth line");
console.log("6th line");
console.log("7th line");
console.log("8th line");
console.log("9th line");